/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthAuthConfirmRouteImport } from './routes/_auth/auth/confirm'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthNoAccessRouteImport } from './routes/_auth/no-access'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthSetPasswordRouteImport } from './routes/_auth/set-password'
import { Route as AuthedHoaBoardRouteImport } from './routes/_authed/hoa-board'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedLogsRouteImport } from './routes/_authed/logs'
import { Route as AuthedMaintenanceRouteImport } from './routes/_authed/maintenance'
import { Route as AuthedPresidencyRouteImport } from './routes/_authed/presidency'
import { Route as AuthedResidentialRouteImport } from './routes/_authed/residential'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedSecurityRouteImport } from './routes/_authed/security'
import { Route as AuthedTreasuryRouteImport } from './routes/_authed/treasury'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ReportsPdfRouteImport } from './routes/reports/pdf'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNoAccessRoute = AuthNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedHoaBoardRoute = AuthedHoaBoardRouteImport.update({
  id: '/hoa-board',
  path: '/hoa-board',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedLogsRoute = AuthedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMaintenanceRoute = AuthedMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPresidencyRoute = AuthedPresidencyRouteImport.update({
  id: '/presidency',
  path: '/presidency',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedResidentialRoute = AuthedResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSecurityRoute = AuthedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedTreasuryRoute = AuthedTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPdfRoute = ReportsPdfRouteImport.update({
  id: '/reports/pdf',
  path: '/reports/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthConfirmRoute = AuthAuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof AuthLoginRoute
  '/no-access': typeof AuthNoAccessRoute
  '/set-password': typeof AuthSetPasswordRoute
  '/hoa-board': typeof AuthedHoaBoardRoute
  '/logs': typeof AuthedLogsRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/presidency': typeof AuthedPresidencyRoute
  '/residential': typeof AuthedResidentialRoute
  '/security': typeof AuthedSecurityRoute
  '/treasury': typeof AuthedTreasuryRoute
  '/api/og': typeof ApiOgRoute
  '/reports/pdf': typeof ReportsPdfRoute
  '/auth/confirm': typeof AuthAuthConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof AuthLoginRoute
  '/no-access': typeof AuthNoAccessRoute
  '/set-password': typeof AuthSetPasswordRoute
  '/hoa-board': typeof AuthedHoaBoardRoute
  '/logs': typeof AuthedLogsRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/presidency': typeof AuthedPresidencyRoute
  '/residential': typeof AuthedResidentialRoute
  '/security': typeof AuthedSecurityRoute
  '/treasury': typeof AuthedTreasuryRoute
  '/api/og': typeof ApiOgRoute
  '/reports/pdf': typeof ReportsPdfRoute
  '/auth/confirm': typeof AuthAuthConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/no-access': typeof AuthNoAccessRoute
  '/_auth/set-password': typeof AuthSetPasswordRoute
  '/_authed/hoa-board': typeof AuthedHoaBoardRoute
  '/_authed/logs': typeof AuthedLogsRoute
  '/_authed/maintenance': typeof AuthedMaintenanceRoute
  '/_authed/presidency': typeof AuthedPresidencyRoute
  '/_authed/residential': typeof AuthedResidentialRoute
  '/_authed/security': typeof AuthedSecurityRoute
  '/_authed/treasury': typeof AuthedTreasuryRoute
  '/api/og': typeof ApiOgRoute
  '/reports/pdf': typeof ReportsPdfRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_auth/auth/confirm': typeof AuthAuthConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-access'
    | '/set-password'
    | '/hoa-board'
    | '/logs'
    | '/maintenance'
    | '/presidency'
    | '/residential'
    | '/security'
    | '/treasury'
    | '/api/og'
    | '/reports/pdf'
    | '/auth/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-access'
    | '/set-password'
    | '/hoa-board'
    | '/logs'
    | '/maintenance'
    | '/presidency'
    | '/residential'
    | '/security'
    | '/treasury'
    | '/api/og'
    | '/reports/pdf'
    | '/auth/confirm'
  id:
    | '__root__'
    | '/_auth'
    | '/_authed'
    | '/_auth/login'
    | '/_auth/no-access'
    | '/_auth/set-password'
    | '/_authed/hoa-board'
    | '/_authed/logs'
    | '/_authed/maintenance'
    | '/_authed/presidency'
    | '/_authed/residential'
    | '/_authed/security'
    | '/_authed/treasury'
    | '/api/og'
    | '/reports/pdf'
    | '/_authed/'
    | '/_auth/auth/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
  ReportsPdfRoute: typeof ReportsPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/no-access': {
      id: '/_auth/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof AuthNoAccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/set-password': {
      id: '/_auth/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/hoa-board': {
      id: '/_authed/hoa-board'
      path: '/hoa-board'
      fullPath: '/hoa-board'
      preLoaderRoute: typeof AuthedHoaBoardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/logs': {
      id: '/_authed/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthedLogsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/maintenance': {
      id: '/_authed/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthedMaintenanceRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/presidency': {
      id: '/_authed/presidency'
      path: '/presidency'
      fullPath: '/presidency'
      preLoaderRoute: typeof AuthedPresidencyRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/residential': {
      id: '/_authed/residential'
      path: '/residential'
      fullPath: '/residential'
      preLoaderRoute: typeof AuthedResidentialRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/security': {
      id: '/_authed/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthedSecurityRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/treasury': {
      id: '/_authed/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof AuthedTreasuryRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/pdf': {
      id: '/reports/pdf'
      path: '/reports/pdf'
      fullPath: '/reports/pdf'
      preLoaderRoute: typeof ReportsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth/confirm': {
      id: '/_auth/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthAuthConfirmRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNoAccessRoute: typeof AuthNoAccessRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  AuthAuthConfirmRoute: typeof AuthAuthConfirmRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthNoAccessRoute: AuthNoAccessRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  AuthAuthConfirmRoute: AuthAuthConfirmRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(AuthRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedHoaBoardRoute: typeof AuthedHoaBoardRoute
  AuthedLogsRoute: typeof AuthedLogsRoute
  AuthedMaintenanceRoute: typeof AuthedMaintenanceRoute
  AuthedPresidencyRoute: typeof AuthedPresidencyRoute
  AuthedResidentialRoute: typeof AuthedResidentialRoute
  AuthedSecurityRoute: typeof AuthedSecurityRoute
  AuthedTreasuryRoute: typeof AuthedTreasuryRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedHoaBoardRoute: AuthedHoaBoardRoute,
  AuthedLogsRoute: AuthedLogsRoute,
  AuthedMaintenanceRoute: AuthedMaintenanceRoute,
  AuthedPresidencyRoute: AuthedPresidencyRoute,
  AuthedResidentialRoute: AuthedResidentialRoute,
  AuthedSecurityRoute: AuthedSecurityRoute,
  AuthedTreasuryRoute: AuthedTreasuryRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(AuthedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
  ReportsPdfRoute: ReportsPdfRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { createStart } from '@tanstack/react-start'
import type { getRouter } from './router.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
