/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedTreasuryRouteImport } from './routes/_authed/treasury'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSecurityRouteImport } from './routes/_authed/security'
import { Route as AuthedPresidencyRouteImport } from './routes/_authed/presidency'
import { Route as AuthedMaintenanceRouteImport } from './routes/_authed/maintenance'
import { Route as AuthedHoaBoardRouteImport } from './routes/_authed/hoa-board'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminResidentialRouteImport } from './routes/_authed/admin/residential'
import { Route as AuthedAdminAuditRouteImport } from './routes/_authed/admin/audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTreasuryRoute = AuthedTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSecurityRoute = AuthedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPresidencyRoute = AuthedPresidencyRouteImport.update({
  id: '/presidency',
  path: '/presidency',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMaintenanceRoute = AuthedMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHoaBoardRoute = AuthedHoaBoardRouteImport.update({
  id: '/hoa-board',
  path: '/hoa-board',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminResidentialRoute = AuthedAdminResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAuditRoute = AuthedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/hoa-board': typeof AuthedHoaBoardRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/presidency': typeof AuthedPresidencyRoute
  '/security': typeof AuthedSecurityRoute
  '/settings': typeof AuthedSettingsRoute
  '/treasury': typeof AuthedTreasuryRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/residential': typeof AuthedAdminResidentialRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/hoa-board': typeof AuthedHoaBoardRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/presidency': typeof AuthedPresidencyRoute
  '/security': typeof AuthedSecurityRoute
  '/settings': typeof AuthedSettingsRoute
  '/treasury': typeof AuthedTreasuryRoute
  '/': typeof AuthedIndexRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/residential': typeof AuthedAdminResidentialRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/hoa-board': typeof AuthedHoaBoardRoute
  '/_authed/maintenance': typeof AuthedMaintenanceRoute
  '/_authed/presidency': typeof AuthedPresidencyRoute
  '/_authed/security': typeof AuthedSecurityRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/treasury': typeof AuthedTreasuryRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/audit': typeof AuthedAdminAuditRoute
  '/_authed/admin/residential': typeof AuthedAdminResidentialRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/hoa-board'
    | '/maintenance'
    | '/presidency'
    | '/security'
    | '/settings'
    | '/treasury'
    | '/admin/audit'
    | '/admin/residential'
    | '/admin/users'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/hoa-board'
    | '/maintenance'
    | '/presidency'
    | '/security'
    | '/settings'
    | '/treasury'
    | '/'
    | '/admin/audit'
    | '/admin/residential'
    | '/admin/users'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/admin'
    | '/_authed/hoa-board'
    | '/_authed/maintenance'
    | '/_authed/presidency'
    | '/_authed/security'
    | '/_authed/settings'
    | '/_authed/treasury'
    | '/_authed/'
    | '/_authed/admin/audit'
    | '/_authed/admin/residential'
    | '/_authed/admin/users'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/treasury': {
      id: '/_authed/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof AuthedTreasuryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/security': {
      id: '/_authed/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthedSecurityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/presidency': {
      id: '/_authed/presidency'
      path: '/presidency'
      fullPath: '/presidency'
      preLoaderRoute: typeof AuthedPresidencyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/maintenance': {
      id: '/_authed/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthedMaintenanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hoa-board': {
      id: '/_authed/hoa-board'
      path: '/hoa-board'
      fullPath: '/hoa-board'
      preLoaderRoute: typeof AuthedHoaBoardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/residential': {
      id: '/_authed/admin/residential'
      path: '/residential'
      fullPath: '/admin/residential'
      preLoaderRoute: typeof AuthedAdminResidentialRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthedAdminAuditRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminAuditRoute: typeof AuthedAdminAuditRoute
  AuthedAdminResidentialRoute: typeof AuthedAdminResidentialRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminAuditRoute: AuthedAdminAuditRoute,
  AuthedAdminResidentialRoute: AuthedAdminResidentialRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedHoaBoardRoute: typeof AuthedHoaBoardRoute
  AuthedMaintenanceRoute: typeof AuthedMaintenanceRoute
  AuthedPresidencyRoute: typeof AuthedPresidencyRoute
  AuthedSecurityRoute: typeof AuthedSecurityRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTreasuryRoute: typeof AuthedTreasuryRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedHoaBoardRoute: AuthedHoaBoardRoute,
  AuthedMaintenanceRoute: AuthedMaintenanceRoute,
  AuthedPresidencyRoute: AuthedPresidencyRoute,
  AuthedSecurityRoute: AuthedSecurityRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTreasuryRoute: AuthedTreasuryRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
