/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedTreasuryRouteImport } from './routes/_authed/treasury'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSecurityRouteImport } from './routes/_authed/security'
import { Route as AuthedPresidencyRouteImport } from './routes/_authed/presidency'
import { Route as AuthedMaintenanceRouteImport } from './routes/_authed/maintenance'
import { Route as AuthedAdminRouteImport } from './routes/_authed/_admin'
import { Route as ApiUserProfileRouteImport } from './routes/api/user/profile'
import { Route as ApiOwnersSplatRouteImport } from './routes/api/owners/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedAdminAdministrationRouteImport } from './routes/_authed/_admin/administration'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTreasuryRoute = AuthedTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSecurityRoute = AuthedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPresidencyRoute = AuthedPresidencyRouteImport.update({
  id: '/presidency',
  path: '/presidency',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMaintenanceRoute = AuthedMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user/profile',
  path: '/api/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOwnersSplatRoute = ApiOwnersSplatRouteImport.update({
  id: '/api/owners/$',
  path: '/api/owners/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminAdministrationRoute =
  AuthedAdminAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/presidency': typeof AuthedPresidencyRoute
  '/security': typeof AuthedSecurityRoute
  '/settings': typeof AuthedSettingsRoute
  '/treasury': typeof AuthedTreasuryRoute
  '/': typeof AuthedIndexRoute
  '/administration': typeof AuthedAdminAdministrationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/owners/$': typeof ApiOwnersSplatRoute
  '/api/user/profile': typeof ApiUserProfileRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/maintenance': typeof AuthedMaintenanceRoute
  '/presidency': typeof AuthedPresidencyRoute
  '/security': typeof AuthedSecurityRoute
  '/settings': typeof AuthedSettingsRoute
  '/treasury': typeof AuthedTreasuryRoute
  '/': typeof AuthedIndexRoute
  '/administration': typeof AuthedAdminAdministrationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/owners/$': typeof ApiOwnersSplatRoute
  '/api/user/profile': typeof ApiUserProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/_admin': typeof AuthedAdminRouteWithChildren
  '/_authed/maintenance': typeof AuthedMaintenanceRoute
  '/_authed/presidency': typeof AuthedPresidencyRoute
  '/_authed/security': typeof AuthedSecurityRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/treasury': typeof AuthedTreasuryRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/_admin/administration': typeof AuthedAdminAdministrationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/owners/$': typeof ApiOwnersSplatRoute
  '/api/user/profile': typeof ApiUserProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/maintenance'
    | '/presidency'
    | '/security'
    | '/settings'
    | '/treasury'
    | '/'
    | '/administration'
    | '/api/auth/$'
    | '/api/owners/$'
    | '/api/user/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/maintenance'
    | '/presidency'
    | '/security'
    | '/settings'
    | '/treasury'
    | '/'
    | '/administration'
    | '/api/auth/$'
    | '/api/owners/$'
    | '/api/user/profile'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/_admin'
    | '/_authed/maintenance'
    | '/_authed/presidency'
    | '/_authed/security'
    | '/_authed/settings'
    | '/_authed/treasury'
    | '/_authed/'
    | '/_authed/_admin/administration'
    | '/api/auth/$'
    | '/api/owners/$'
    | '/api/user/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOwnersSplatRoute: typeof ApiOwnersSplatRoute
  ApiUserProfileRoute: typeof ApiUserProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/treasury': {
      id: '/_authed/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof AuthedTreasuryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/security': {
      id: '/_authed/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthedSecurityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/presidency': {
      id: '/_authed/presidency'
      path: '/presidency'
      fullPath: '/presidency'
      preLoaderRoute: typeof AuthedPresidencyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/maintenance': {
      id: '/_authed/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthedMaintenanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/user/profile': {
      id: '/api/user/profile'
      path: '/api/user/profile'
      fullPath: '/api/user/profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/owners/$': {
      id: '/api/owners/$'
      path: '/api/owners/$'
      fullPath: '/api/owners/$'
      preLoaderRoute: typeof ApiOwnersSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_admin/administration': {
      id: '/_authed/_admin/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthedAdminAdministrationRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminAdministrationRoute: typeof AuthedAdminAdministrationRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminAdministrationRoute: AuthedAdminAdministrationRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedMaintenanceRoute: typeof AuthedMaintenanceRoute
  AuthedPresidencyRoute: typeof AuthedPresidencyRoute
  AuthedSecurityRoute: typeof AuthedSecurityRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTreasuryRoute: typeof AuthedTreasuryRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedMaintenanceRoute: AuthedMaintenanceRoute,
  AuthedPresidencyRoute: AuthedPresidencyRoute,
  AuthedSecurityRoute: AuthedSecurityRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTreasuryRoute: AuthedTreasuryRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOwnersSplatRoute: ApiOwnersSplatRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
